var GAME_LEVELS = [
  ["                                     qq             q                           ",
   "                                    qqqq           qqq                          ",
   "                      qq                          qqqqqq                        ",
   "                     qqqq                                            qqq        ",
   "                              qq                                   qqqqqqq      ",
   "                            qqqqq                                               ",
   "           qq                                                                   ",
   "          qqqq                                  c                               ",
   "                                                c                               ",
   "                                                c                               ",
   "                                              xxxx         c                   x",
   "                           c                  x!!x         c                   x",
   "  xx                       c                 x!!!x v x!!!xxxxx                 x",
   "  x                 c     xxx            c    !!!x!!!x!!!x                     x",
   "  x                xxx                  xxx  !!!!x!!!x!!!!!!                   x",
   "  x  c      xxx                  xxx        !!!!!x!!!x!!!!!!!v   xx          c x",
   "  x@ c c        c       |      |     v | !!!!!!!!x!!!x!!!!!!!!!     | x   c  c x",
   "  xxxxxxxx | xxxx   xxx!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!x!!xxooxxx",
   "         x!!!x  x!!!x x!!!!!!!!!!!!!!!!!!!!!!x       x!!!!!!!!!!!!!!!!!!!xxoox  ",
   "         x!!!x  x!!!x x!!!!!!!!!!!!!!!!!!!!!!x       x!!!!!!!!!!!!!!!!!!!xxxxx  ",
   "         x!!!x  xxxxx x!!!!!!!!!!!!!!!!!!!!!!x       xxxxxxxxxxxxxxxxxxxxx      ",
   "         xxxxx        xxxxxxxxxxxxxxxxxxxxxxxx                                  ",
   "                                                                                ",
   "                                                                                "],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                   ",
   "x           b     b     b     b     b         x                                                                   ",
   "x          b     b     b     b     b          x                                                                   ",
   "x         b     b     b     b     b           x                                                                   ",
   "x        b     b     b     b     b          c x                                                                   ",
   "x       b     b     b     b     b     c     c x                                                                   ",
   "x      b     b     b     b     b      c c   c x                                                                   ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxhxxxx                                                                   ",
   "                                qqq                qq     q                       q                               ",
   "         q                qq   qqqqqq   qqq       qqqqq  qqq        q            qqq                              ",
   "        qqq             qqqqq          qqqqq     qqqqqqq           qqq          qqqqq      q              qq      ",
   "       qqqqq                                                      qqqqq                   qqq     q      qqqq     ",
   "                                                                                                 qqq              ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                              c                         c                       c ",
   "                                      c      c          c     c             c           c                       c ",
   "                                      c     xxxx        c   xxxxx           c   |  v    c   c            c      c ",
   "                   c          c     xxxx             c  x              xpppxxxx!!!!!!xxxxxxxxxxxxx|xxxxxxxoooooxxx",
   "     @          c  c       xxxx                     xxx                xxxxxxxxx!!!!xxxxxxxxxxxxxx!xxxxxxxxoooxxxx",
   "    xxx         c  c c   v     v |  v   | v  v   | v   |  v  v  |  | v xxxxxxxxxx!!xxxxxxxxxxxxxxx!xxxxxxxxxxxxxxx",
   "    xxx  | v  xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!xxx!!!!!!!xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!xxx!!!!!!!xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!xxx!!!!!!!xx!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!xxx!!!!!!!xx!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!xxx!!!!!!!xx!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!xxx!!!!!!!xx!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!xxx!!!!!!!xx!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                             x",
   "                                                                                                             x",
   "                                                                                                             x",
   "                                                                                                             x",
   "                                                                                                             x",
   "                                                                                                     s       x",
   "                                                                                                    sss      x",
   "                                          c                                                        sssss     x",
   "       c          c         c             c          c           c          c          c          sssssss    x",
   "       c     c    c         c     c    c  c    c     c      c    c   c   c  c     c    c    c      s   s  c  x",
   "       c  c  c v  c    c    c  c  c  v c  c c  c  v  c   c  c  v c   c c c  c  v  c    c    c      s s s  c  x",
   "xxxxxxxxxxxxxxx!!xxxxxxxxxxxxxxxxxxx!!xxxxxxxxxxxx!!xxxxxxxxxx!!xxxxxxxxxxxxxxx!!xxxxxxxxxxxxxxoooxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxoxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "======           bbbb      bbbb      bbbb      bbbb  x                                                       x",
   "======          bbbb      bbbb      bbbb      bbbb   x                                                       x",
   "======         bbbb      bbbb      bbbb      bbbb    x                                                       x",
   "======        bbbb      bbbb      bbbb      bbbb    hx                                                       x",
   "======       bbbb      bbbb      bbbb      bbbb    xxx                                                       x",
   "======      bbbb      bbbb      bbbb      bbbb                                                               x",
   "======  @  bbbb      bbbb      bbbb      bbbb                                                                x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx|xxxvxxx|xxxvxxx|xxxvxxx|xxxxxvxxxxx|xxxxxxv|xxxxxxpxxx"],
  ["                x=  x                                           x                                             ",
   "                x  =x      o   o oooo o  o                      x                                             ",
   "                x=  x       o o  o  o o  o           q          x                                             ",
   "      ooo       x  =x        o   o  o o  o   q      qqq         x                                             ",
   "     o   o      x=  x        o   o  o o  o  qqq                 x                                             ",
   "         o      x  =x        o   oooo oooo                      x                                             ",
   "        o       x=  x                             s             x                                             ",
   "       o        x  =x      o o o ooo o   o       sss            x                                             ",
   "       o        x=  x      o o o  o  oo  o      sssss           x                                             ",
   "                x  =x      o o o  o  o o o     sssssss          x                                             ",
   "       o        x=  x      o o o  o  o  oo    sssssssss     c   x                                             ",
   "                x  =x c    ooooo ooo o c o   sssssssssss    c   x                                             ",
   "                x=  x c   c            c  c   s       s     c   x                                             ",
   "                x  =x c   c      c     c  c  @s   s   s     c   x                                             ",
   "!!!!!!!!!!!!!!!!xxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxxxppxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!xxxxxxxxxxxxx!xxxxxxxx!xxxxqqxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!xxxxxxxxxxxqqxxxxxxxxx!xxxxxxxxxx!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxqqqqxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
